import React from 'react'

export default function RecommendationPanel({ recommendation, risk }) {
  const borderColor = risk === 'DANGER' ? 'border-red-500/40' : risk === 'WARNING' ? 'border-yellow-400/40' : 'border-army-accent/30'
  const labelColor = risk === 'DANGER' ? 'text-red-400' : risk === 'WARNING' ? 'text-yellow-400' : 'text-army-accent'

  return (
    <div className={`bg-army-panel rounded-lg border p-4 flex flex-col gap-3 ${borderColor}`}>
      <div className="flex items-center gap-2">
        <span className="text-lg">🤖</span>
        <span className="text-xs font-bold tracking-widest text-gray-400">AI RESCUE RECOMMENDATION</span>
        <span className={`ml-auto text-xs font-mono ${labelColor}`}>LLM OUTPUT</span>
      </div>
      <div className={`text-sm leading-relaxed font-mono ${risk === 'DANGER' ? 'text-red-300' : risk === 'WARNING' ? 'text-yellow-300' : 'text-green-300'}`}>
        {recommendation}
      </div>
      <div className="text-xs text-gray-600 font-mono border-t border-gray-800 pt-2">
        Generated by ROVER-AI v2.1 · Updated every 2s
      </div>
    </div>
  )
}
